name: Deploy

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Clean up workspace
      continue-on-error: true
      run: rm -rf ./*
    - name: Clean up docker
      continue-on-error: true
      run: docker rm -f contribute-me-container
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      env:
        SECRET: ${{ secrets.FLAG }}
        REPO: "https://github.com/${{ github.event.repository.full_name }}"
        REPO_NAME: ${{ github.event.repository.name }}
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        envs: SECRET, REPO, REPO_NAME
        script_stop: true
        script: |
          git clone $REPO
          cd $REPO_NAME
          git fetch origin
          docker build . -t doublevkay/contribute-me --build-arg secret=$SECRET --build-arg repo=$REPO
          docker run -p 8080:8080 -d doublevkay/contribute-me --name contribute-me-container
          echo "Deployed successfully"
          