name: Deploy

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Clean up workspace
      continue-on-error: true
      run: |
        rm -rf ~/*
