name: Echo Test

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  echo-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Echo Test
        run: echo "Echo test"
