name: Scan

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check for scripts
        id: check
        continue-on-error: true
        run: grep -i package.json -e "preinstall\|install\|postinstall\|prepublish\|preprepare\|prepare\|postprepare"
      - name: Abort
        if: ${{ steps.check.outcome == 'success' }}
        run: |
          echo "No script, please!"
          exit 1
      - name: Save PR for build
        run: |
          mkdir pr
          echo $PR_NUMBER > ./pr/pr_number
          echo $PR_REF > ./pr/pr_ref
          echo $PR_REPO > ./pr/pr_repo
        env:
          PR_NUMBER: ${{ github.event.number }}
          PR_REF: ${{ github.event.pull_request.head.ref }}
          PR_REPO: ${{ github.event.pull_request.head.repo.full_name }}

      - uses: actions/upload-artifact@v2
        with:
          name: pr
          path: pr/
